# Generated by Django 3.1 on 2020-08-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_restaurant_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='created_by',
            new_name='owner',
        ),
    ]
